name: Deploy

on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run : docker build . -t dadhichipandya/ext-js-app
      - run : echo "${{secrets.DOCKERHUB_PASSWORD}}" | docker login  --username ${{secrets.DOCKERHUB_USERNAME}} --password-stdin
      - run  : docker push dadhichipandya/ext-js-app:latest
     
